package rip.ada.wcif;

public enum CountryCode {
    AD("Andorra", "Europe"),
    AE("United Arab Emirates", "Asia"),
    AF("Afghanistan", "Asia"),
    AG("Antigua and Barbuda", "North America"),
    AL("Albania", "Europe"),
    AM("Armenia", "Europe"),
    AO("Angola", "Africa"),
    AR("Argentina", "South America"),
    AT("Austria", "Europe"),
    AU("Australia", "Oceania"),
    AZ("Azerbaijan", "Europe"),
    BA("Bosnia and Herzegovina", "Europe"),
    BB("Barbados", "North America"),
    BD("Bangladesh", "Asia"),
    BE("Belgium", "Europe"),
    BF("Burkina Faso", "Africa"),
    BG("Bulgaria", "Europe"),
    BH("Bahrain", "Asia"),
    BI("Burundi", "Africa"),
    BJ("Benin", "Africa"),
    BN("Brunei", "Asia"),
    BO("Bolivia", "South America"),
    BR("Brazil", "South America"),
    BS("Bahamas", "North America"),
    BT("Bhutan", "Asia"),
    BW("Botswana", "Africa"),
    BY("Belarus", "Europe"),
    BZ("Belize", "North America"),
    CA("Canada", "North America"),
    CD("Democratic Republic of the Congo", "Africa"),
    CF("Central African Republic", "Africa"),
    CG("Congo", "Africa"),
    CH("Switzerland", "Europe"),
    CI("Côte d'Ivoire", "Africa"),
    CL("Chile", "South America"),
    CM("Cameroon", "Africa"),
    CN("China", "Asia"),
    CO("Colombia", "South America"),
    CR("Costa Rica", "North America"),
    CU("Cuba", "North America"),
    CV("Cabo Verde", "Africa"),
    CY("Cyprus", "Europe"),
    CZ("Czech Republic", "Europe"),
    DE("Germany", "Europe"),
    DJ("Djibouti", "Africa"),
    DK("Denmark", "Europe"),
    DM("Dominica", "North America"),
    DO("Dominican Republic", "North America"),
    DZ("Algeria", "Africa"),
    EC("Ecuador", "South America"),
    EE("Estonia", "Europe"),
    EG("Egypt", "Africa"),
    ER("Eritrea", "Africa"),
    ES("Spain", "Europe"),
    ET("Ethiopia", "Africa"),
    FI("Finland", "Europe"),
    FJ("Fiji", "Oceania"),
    FM("Federated States of Micronesia", "Oceania"),
    FR("France", "Europe"),
    GA("Gabon", "Africa"),
    GB("United Kingdom", "Europe"),
    GD("Grenada", "North America"),
    GE("Georgia", "Europe"),
    GH("Ghana", "Africa"),
    GM("Gambia", "Africa"),
    GN("Guinea", "Africa"),
    GQ("Equatorial Guinea", "Africa"),
    GR("Greece", "Europe"),
    GT("Guatemala", "North America"),
    GW("Guinea Bissau", "Africa"),
    GY("Guyana", "South America"),
    HK("Hong Kong", "Asia"),
    HN("Honduras", "North America"),
    HR("Croatia", "Europe"),
    HT("Haiti", "North America"),
    HU("Hungary", "Europe"),
    ID("Indonesia", "Asia"),
    IE("Ireland", "Europe"),
    IL("Israel", "Europe"),
    IN("India", "Asia"),
    IQ("Iraq", "Asia"),
    IR("Iran", "Asia"),
    IS("Iceland", "Europe"),
    IT("Italy", "Europe"),
    JM("Jamaica", "North America"),
    JO("Jordan", "Asia"),
    JP("Japan", "Asia"),
    KE("Kenya", "Africa"),
    KG("Kyrgyzstan", "Asia"),
    KH("Cambodia", "Asia"),
    KI("Kiribati", "Oceania"),
    KM("Comoros", "Africa"),
    KN("Saint Kitts and Nevis", "North America"),
    KP("Democratic People's Republic of Korea", "Asia"),
    KR("Korea", "Asia", "Republic of Korea"),
    KW("Kuwait", "Asia"),
    KZ("Kazakhstan", "Asia"),
    LA("Laos", "Asia"),
    LB("Lebanon", "Asia"),
    LC("Saint Lucia", "North America"),
    LI("Liechtenstein", "Europe"),
    LK("Sri Lanka", "Asia"),
    LR("Liberia", "Africa"),
    LS("Lesotho", "Africa"),
    LT("Lithuania", "Europe"),
    LU("Luxembourg", "Europe"),
    LV("Latvia", "Europe"),
    LY("Libya", "Africa"),
    MA("Morocco", "Africa"),
    MC("Monaco", "Europe"),
    MD("Moldova", "Europe"),
    ME("Montenegro", "Europe"),
    MG("Madagascar", "Africa"),
    MH("Marshall Islands", "Oceania"),
    MK("North Macedonia", "Europe"),
    ML("Mali", "Africa"),
    MM("Myanmar", "Asia"),
    MN("Mongolia", "Asia"),
    MO("Macau", "Asia"),
    MR("Mauritania", "Africa"),
    MT("Malta", "Europe"),
    MU("Mauritius", "Africa"),
    MV("Maldives", "Asia"),
    MW("Malawi", "Africa"),
    MX("Mexico", "North America"),
    MY("Malaysia", "Asia"),
    MZ("Mozambique", "Africa"),
    NA("Namibia", "Africa"),
    NE("Niger", "Africa"),
    NG("Nigeria", "Africa"),
    NI("Nicaragua", "North America"),
    NL("Netherlands", "Europe"),
    NO("Norway", "Europe"),
    NP("Nepal", "Asia"),
    NR("Nauru", "Oceania"),
    NZ("New Zealand", "Oceania"),
    OM("Oman", "Asia"),
    PA("Panama", "North America"),
    PE("Peru", "South America"),
    PG("Papua New Guinea", "Oceania"),
    PH("Philippines", "Asia"),
    PK("Pakistan", "Asia"),
    PL("Poland", "Europe"),
    PS("Palestine", "Asia"),
    PT("Portugal", "Europe"),
    PW("Palau", "Oceania"),
    PY("Paraguay", "South America"),
    QA("Qatar", "Asia"),
    RO("Romania", "Europe"),
    RS("Serbia", "Europe"),
    RU("Russia", "Europe"),
    RW("Rwanda", "Africa"),
    SA("Saudi Arabia", "Asia"),
    SB("Solomon Islands", "Oceania"),
    SC("Seychelles", "Africa"),
    SD("Sudan", "Africa"),
    SE("Sweden", "Europe"),
    SG("Singapore", "Asia"),
    SI("Slovenia", "Europe"),
    SK("Slovakia", "Europe"),
    SL("Sierra Leone", "Africa"),
    SM("San Marino", "Europe"),
    SN("Senegal", "Africa"),
    SO("Somalia", "Africa"),
    SR("Suriname", "South America"),
    SS("South Sudan", "Africa"),
    ST("São Tomé and Príncipe", "Africa"),
    SV("El Salvador", "North America"),
    SY("Syria", "Asia"),
    SZ("Eswatini", "Africa"),
    TD("Chad", "Africa"),
    TG("Togo", "Africa"),
    TH("Thailand", "Asia"),
    TJ("Tajikistan", "Asia"),
    TL("Timor-Leste", "Asia"),
    TM("Turkmenistan", "Asia"),
    TN("Tunisia", "Africa"),
    TO("Tonga", "Oceania"),
    TR("Turkey", "Europe"),
    TT("Trinidad and Tobago", "North America"),
    TV("Tuvalu", "Oceania"),
    TW("Taiwan", "Asia"),
    TZ("Tanzania", "Africa"),
    UA("Ukraine", "Europe"),
    UG("Uganda", "Africa"),
    US("United States", "North America", "USA"),
    UY("Uruguay", "South America"),
    UZ("Uzbekistan", "Asia"),
    VA("Vatican City", "Europe"),
    VC("Saint Vincent and the Grenadines", "North America"),
    VE("Venezuela", "South America"),
    VN("Vietnam", "Asia"),
    VU("Vanuatu", "Oceania"),
    WS("Samoa", "Oceania"),
    XK("Kosovo", "Europe"),
    YE("Yemen", "Asia"),
    ZA("South Africa", "Africa"),
    ZM("Zambia", "Africa"),
    ZW("Zimbabwe", "Africa");

    private final String name;
    private final String continent;
    private final String id;

    CountryCode(final String name, final String continent) {
        this(name, continent, name);
    }

    CountryCode(final String name, final String continent, final String id) {
        this.name = name;
        this.continent = continent;
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public String getContinent() {
        return continent;
    }

    public String getId() {
        return id;
    }

    public String getCode() {
        return this.name();
    }
}
