name: Gradle CI

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build & Test
    steps:
      - uses: actions/checkout@v2
      - name: Set up java
        uses: actions/setup-java@v2
        with:
          java-version: 21
          distribution: 'zulu'
      - name: Build
        run: ./gradlew build
      - name: Test
        run: ./gradlew test
      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: reports
          path: build/reports